version: "3.8"
services:
  frontend:
    build: .
    container_name: "vue3-docker"
    env_file:
      - .env
    ports:
      - '3000:3000'
    volumes:
      - .:/var/www/html/vue3-docker
      - "/var/www/html/vue3-docker/node_modules"
